# -*- coding: utf-8 -*- 
# @Time     : 2019-08-22 10:56
# @Author   : binger

# 对齐关系
ALIGN_LEFT = ALIGN_UP = 0
ALIGN_CENTER = 1
ALIGN_RIGHT = ALIGN_DOWN = 2

# 位置关系
INTERSECTION_HORI = 0
INTERSECTION_VERI = 1

# 元素类型种类
TYPE_BACKGROUND = "B"  # 背景
TYPE_GRAPH = "G"
TYPE_LOGO = "L"
TYPE_RELATION = "R"
TYPE_TEXT = "T"
TYPE_OTHER = "O"

# 具体种类
TYPE_GRAPH_MAIN = "G1"
TYPE_GRAPH_SUB = "G2"
TYPE_GRAPH_DECORATION = "G3"
TYPE_RELATION_AREA = "R1"
TYPE_RELATION_LINE = "R2"
TYPE_TEXT_TITLE_LIST = ["T1", "T2"]
